### ISSUE TITLE
Can't build on Ubuntu 14.10

### ISSUE THREAD

**Issue by jonty789** [CarlKenner/dolphin#39]
Hi

I am trying to compile this on Ubuntu 14.10 however it can't build.

It seems to make errors at dolphin/Source/Core/VideoBackends/OGL/Render.cpp.
One of the error is 

: warning: unused variable ‘ElementArrayBufferBinding’ [-Wunused-variable]
  static int ElementArrayBufferBinding, ArrayBufferBinding;

I have successfully compiled the official dolphin emulator github so that means I should have all the required build deps. I am trying this because I would like to try out wii u support.
Any ideas please?
Thanks :)

**Comment by feilen** [comment]
I'm the Linux porting developer.

Try building with these flags: 

```
cmake -DCMAKE_CXX_FLAGS="-fpermissive -fno-inline-functions" -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=true
```

If you could give me the actual errors that would be helpful in narrowing it down. The ones that start with `error:` are what I'm looking for.

You also should try building from my git explicitly, as the versions there are more or less guaranteed to build on Linux.

**Comment by jonty789** [comment]
Hi

Thanks for the fast reply! I will try that again and your github one but atm github is being slow to clone.

I will reply back with errors when it done.

Thanks

**Comment by jonty789** [comment]
Ok I have cloned your github and tried to build it. I have tried the build flags you suggested but I am still getting errors. The errors are 

 error: ‘struct VideoConfig’ has no member named ‘bDumpFrames’
   if (g_ActiveConfig.bDumpFrames)
                      ^
error: ‘GL_REPORT_ERROR’ was not declared in this scope
    if (GL_REPORT_ERROR() == GL_NO_ERROR)

Thanks

**Comment by feilen** [comment]
Have you got the Oculus SDK installed into Externals/ or your system?

Also, what file is that error in?

**Comment by jonty789** [comment]
I don't have Oculus SDK installed and the file is dolphin/Source/Core/VideoBackends/OGL/Render.cpp

**Comment by feilen** [comment]
You will need the Oculus SDK to build Dolphin VR. (or in theory, you don't
but you won't get VR support)

Install the OculusSDK into Externals/OculusSDK and build it, then try cmake
configure and build again.

**Comment by jonty789** [comment]
Ok I just have tried that but still same error

**Comment by feilen** [comment]
Can you give me the full output from the cmake command? Make sure you empty
the directory you do it in first (or run git clean -fdx)

**Comment by jonty789** [comment]
Ok here is the full output

/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp: In static member function ‘static void OGL::Renderer::Shutdown()’:
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:710:13: warning: unused variable ‘ElementArrayBufferBinding’ [-Wunused-variable]
  static int ElementArrayBufferBinding, ArrayBufferBinding;
             ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:710:40: warning: unused variable ‘ArrayBufferBinding’ [-Wunused-variable]
  static int ElementArrayBufferBinding, ArrayBufferBinding;
                                        ^
In file included from /home/jonathan/Downloads/dolphin/Source/Core/Common/Common.h:152:0,
                 from /home/jonathan/Downloads/dolphin/Builds/Source/CMakeFiles/pch.dir/pch.h:74,
                 from <command-line>:0:
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp: In member function ‘virtual void OGL::Renderer::SetViewport()’:
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:97:51: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘double’ [-Wformat=]
   GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__); \
                                                   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:104:30: note: in expansion of macro ‘GENERIC_LOG’
 #define INFO_LOG(t,...) do { GENERIC_LOG(LogTypes::t, LogTypes::LINFO, __VA_ARGS__) } while (0)
                              ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1319:3: note: in expansion of macro ‘INFO_LOG’
   INFO_LOG(VR, "glViewport(%d, %d,   %d, %d)", ceil(X), ceil(Y), ceil(Width), ceil(Height));
   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:97:51: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘double’ [-Wformat=]
   GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__); \
                                                   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:104:30: note: in expansion of macro ‘GENERIC_LOG’
 #define INFO_LOG(t,...) do { GENERIC_LOG(LogTypes::t, LogTypes::LINFO, __VA_ARGS__) } while (0)
                              ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1319:3: note: in expansion of macro ‘INFO_LOG’
   INFO_LOG(VR, "glViewport(%d, %d,   %d, %d)", ceil(X), ceil(Y), ceil(Width), ceil(Height));
   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:97:51: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘double’ [-Wformat=]
   GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__); \
                                                   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:104:30: note: in expansion of macro ‘GENERIC_LOG’
 #define INFO_LOG(t,...) do { GENERIC_LOG(LogTypes::t, LogTypes::LINFO, __VA_ARGS__) } while (0)
                              ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1319:3: note: in expansion of macro ‘INFO_LOG’
   INFO_LOG(VR, "glViewport(%d, %d,   %d, %d)", ceil(X), ceil(Y), ceil(Width), ceil(Height));
   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:97:51: warning: format ‘%d’ expects argument of type ‘int’, but argument 9 has type ‘double’ [-Wformat=]
   GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__); \
                                                   ^
/home/jonathan/Downloads/dolphin/Source/Core/Common/Logging/Log.h:104:30: note: in expansion of macro ‘GENERIC_LOG’
 #define INFO_LOG(t,...) do { GENERIC_LOG(LogTypes::t, LogTypes::LINFO, __VA_ARGS__) } while (0)
                              ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1319:3: note: in expansion of macro ‘INFO_LOG’
   INFO_LOG(VR, "glViewport(%d, %d,   %d, %d)", ceil(X), ceil(Y), ceil(Width), ceil(Height));
   ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp: In member function ‘virtual void OGL::Renderer::AsyncTimewarpDraw()’:
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1616:22: error: ‘struct VideoConfig’ has no member named ‘bDumpFrames’
   if (g_ActiveConfig.bDumpFrames)
                      ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1626:24: error: ‘GL_REPORT_ERROR’ was not declared in this scope
    if (GL_REPORT_ERROR() == GL_NO_ERROR)
                        ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp: In member function ‘virtual void OGL::Renderer::SwapImpl(u32, u32, u32, u32, const EFBRectangle&, float)’:
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1761:21: warning: declaration of ‘sourceRc’ shadows a previous local [-Wshadow]
     TargetRectangle sourceRc;
                     ^
/home/jonathan/Downloads/dolphin/Source/Core/VideoBackends/OGL/Render.cpp:1720:16: note: shadowed declaration is here
   EFBRectangle sourceRc;
                ^
Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/build.make:295: recipe for target 'Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/Render.cpp.o' failed
make[2]: *** [Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/Render.cpp.o] Error 1
CMakeFiles/Makefile2:1353: recipe for target 'Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/all' failed
make[1]: *** [Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2


Thanks

**Comment by feilen** [comment]
No, the output from cmake configuration. Please use pastebin.com, and clear
the directory first

**Comment by jonty789** [comment]
Sorry is it CMakeOutput.log?
